import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/BootstrapClient";
import "./globals.css";
import Header from "./Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-bebas-neue">
        <Header />
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
